@startuml
!include ../../copyright.iuml

title Sort Pattern
rectangle "<&question-mark> Sorted" as Sorted
rectangle "<&info> Sort Info" as Sort
rectangle Sorter [
  <&spreadsheet> Sorter
  ....
  ""[ { property, direction } ]""
]

Sorted 0-->> Sort: "sort-info"
Sort 0-->> Sorter: "sorter"
Sorter 0-->> Sorted: "sorts"
@enduml
