@startuml
!include ../../../copyright.iuml

title Configure Offset Pagination
actor Client
participant "<&eye> Pagination" as Pagination

Client -> Pagination: POST
hnote over Pagination #lightblue: ""{ size, start }""
Pagination --> Client: 303 See Other
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""location:"" | //Paged Resource URI// |
end note

@enduml
