@startuml
!include ../relations.puml

title Offset Page Pattern

rectangle PageInfo [
  <&info> Page Info
  ....
  ""current""
  ""pages""
  ""size""
]
rectangle Pagination [
  <&eye> Pagination
  ....
  ""size""
  ""start""
]

Paged 0-->> PageInfo: "page-info"
PageInfo 0-->> Pagination: "paginator"
Pagination 0-->> Paged: "paginates"

@enduml
