@startuml
!include ../../../copyright.iuml

title Configure Cursor
actor Client
participant "<&eye> Cursor" as Cursor
participant "<&question-mark> Cursor Entry" as CursorEntry

Client -> CursorEntry: GET
CursorEntry --> Client: 200 OK
hnote over Client #darkseagreen: ""{ cursorMark }""
Client -> Cursor: POST
hnote over Cursor #lightblue
 ""{""
 ""  [before|after]: cursorMark,""
 ""  *limit,""
 ""  *size""
 ""}""

 //*optional//
end note
Cursor --> Client: 303 See Other
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""location:"" | //Paged Resource URI// |
end note

@enduml
