@startuml
!include ../../copyright.iuml

title Trigger Action

actor Client
participant "<&arrow-circle-right> Action" as Action

Client -> Action: POST
Action --> Client: 303 See Other
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""Location"" | //URL// |
end note
group failure: rejected
  Action -->o Client: 409 Conflict
end

@enduml