@startuml
!include ../../copyright.iuml

title Trigger Action

actor Client
participant "<&arrow-circle-right> Action" as Action

Client -> Action: POST
Action --> Client: 204 No Content
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""Location"" | //URL// |
end note

@enduml