@startuml
!include ../../copyright.iuml

title Discovery

actor Client
participant "<&transfer> Representation" as Representation

Client -> Representation: HEAD
Representation --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""profile:"" | ""<https://level3.rest/profiles/mixins/representation>"", |
  | | ""<other-profile>"" |
end note

@enduml
