@startuml
!include ../../copyright.iuml

title Omit Representation

actor Client
participant "<&transfer> Representation" as Representation

Client -> Representation: PUT / POST / PATCH
rnote right #lightblue
  <#lightblue,lightblue>|= Header |= Value |
  | ""Prefer"" | ""return=minimal"" |
end note
Representation --> Client: 204 No Content / 201 Created
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""Preference-Applied"" | ""return=minimal"" |
end note

@enduml