@startuml
!include ../../copyright.iuml

title Omit Representation

actor Client
participant "<&transfer> Representation" as Representation

Client -> Representation: PUT / POST / PATCH
rnote right #lightblue
  <#lightblue,lightblue>|= Header |= Value |
  | ""Prefer:"" | ""return=minimal"" |
end note
Representation --> Client: 201 Created / 204 No Content / 3xx redirect
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""Preference-Applied:"" | ""return=minimal"" |
  | *""Location:""   | //URL to the full representation// |
  | | |
  | *//for POST operations//| |
end note

@enduml