@startuml
!include ../../copyright.iuml

title Discovery

actor Client
participant "<&data-transfer-download> Content" as Content

Client -> Content: HEAD
Content --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""accept-ranges:"" | ""bytes"" //or// ""none"" |
  | ""allow:"" | ""HEAD,GET,""*""PUT,""*""DELETE"" |
  | ""content-length:"" | //byte-count// |
  | ""content-type:"" | //media-type// |
  | ""content-disposition:"" | //disposition// |
  | ""profile:"" | ""<https://level3.rest/profiles/content>"" |
  | | |
  | | //*optional//|
end note

@enduml
