@startuml
!include ../../copyright.iuml

title Fail-Fast Content Range
actor Client
participant "<&data-transfer-download> Content + <&badge> Entity" as Content

Client -> Content: GET / HEAD
Content --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""accept-ranges:"" | ""bytes"" |
  | ""etag:"" | //entity-tag// |
  | ""content-length:"" | //byte-count// |
  | ""content-type:"" | //media-type// |
  | ""last-modified:"" | //HTTP-date// |
  | ""content-disposition:"" | //disposition// |
  | ""profile:"" | ""<https://level3.rest/profiles/content>,"" |
  | | ""<https://level3.rest/profiles/mixins/entity>"" |
end note
...
Client -> Content: GET
rnote right #lightblue
  <#lightblue,lightblue>|= Header |= Value |
  | ""range:"" | ""bytes=""//byte-range// |
  | ""if-unmodified-since:"" | //HTTP-date// |
  | ""if-match:"" | //entity-tag// |
end note
Content --> Client: 206 Partial Content
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""content-length:"" | //byte-count// |
  | ""content-range:"" | ""bytes ""//byte-range//""/""//total// |
end note
hnote over Client #darkseagreen: ""...partial bytes...""
group failure: rejected
  Content -->o Client: 409 Conflict
  Content -->o Client: 416 Range Not Satisfiable
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""content-range:"" | ""bytes */""//total// |
end note
end

@enduml
