@startuml
!include ../../copyright.iuml

title Fetch Content

actor Client
participant "<&data-transfer-download> Content" as Content

Client -> Content: GET
Content --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""accept-ranges:"" | ""bytes"" //or// ""none"" |
  | ""content-length:"" | //byte-count// |
  | ""content-type:"" | //media-type// |
  | ""content-disposition:"" | //disposition// |
end note
hnote over Client #darkseagreen: ""...bytes...""

@enduml
