@startuml
!include ../copyright.iuml

rectangle "<&home> Root" as Root
rectangle "<&aperture> Nexus" as Nexus
rectangle "<&info> Info" as Info
rectangle "<&code> Data" as Data
rectangle "<&data-transfer-download> Content" as Content
rectangle "<&spreadsheet> Form" as Form
rectangle "<&arrow-circle-right> Action" as Action
rectangle "<&data-transfer-upload> Upload" as Upload
rectangle "<&share> Alias" as Alias

@enduml