@startuml
!include ../../copyright.iuml

title Discovery

actor Client
participant "<&spreadsheet> Form" as Form

Client -> Form: HEAD
Form --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""allow:"" | ""HEAD,GET,POST"" |
  | ""content-type:"" | //content-type// |
  | ""profile:"" | ""<https://level3.rest/profiles/form>"" |
  | *""idempotency-key:"" | ""optional"" //or// ""required"" |

  // *""idempotency-key"" support is optional//
end note

@enduml
