@startuml
!include ../../copyright.iuml

title Submit Form

actor Client
participant "<&spreadsheet> Form" as Form

Client -> Form: GET
Form --> Client: 200 OK
hnote over Client #darkseagreen: schema or ""{ template }""
note over Client
  //Client constructs form with schema//
  //or fills in template//
end note
...
Client -> Form: POST
rnote right #lightblue
  <#lightblue,lightblue>|= Header |= Value |
  | ""content-type:"" | //media-type// |
  | *""idempotency-key:"" | //unique-key// |

  // *If form supports ""idempotency-key""//
end note
hnote over Form #lightsteelblue: ""{ form }""
Form --> Client: 201 Created / 204 No Content
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""location:"" | //Resource URI// |
end note
group failure: form rejected
  Form -->o Client: 400 Bad Request
  Form -->o Client: 403 Forbidden
  Form -->o Client: 415 Unsupported Media Type
  Form -->o Client: 422 Unprocessable Entity
end

@enduml
