@startuml
!include ../../copyright.iuml

title Select Choice
actor Client
participant "<&arrow-circle-right> Choice" as Choice

Client -> Choice: POST
Choice --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""Location:"" | //Chooser URL// |
end note

@enduml
