@startuml
!include ../../copyright.iuml

title Chooser Pattern

rectangle "<&info> | <&aperture> Chooser (Radio or Multi)" as Chooser
rectangle "<&arrow-circle-right> Choice" as Choice
rectangle "<&question-mark> Description" as Description

Chooser 0-->> "0..N" Choice: "choice/chosen"
Choice 0-->> Chooser: "choice-for"
Choice 0-->> Description: "description"

@enduml
