@startuml
!include ../../copyright.iuml

title Metadata Pattern

rectangle "<&data-transfer-download> Content" as Content
rectangle "<&info> Metadata" as Metadata

Content 0-->> Metadata: "metadata"
Metadata 0-->> Content: "content"

@enduml
