@startuml
!include ../../copyright.iuml

title Configure Filtering
actor Client
participant "<&eye> Filtration" as Filtration

Client -> Filtration: POST
hnote over Filtration #lightsteelblue: ""{ filters }""
Filtration --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""location:"" | //Filtered Resource URI// |
end note

@enduml
