@startuml
!include ../../copyright.iuml

title Cache-Aware Fetch

actor Client
participant "<&badge> Entity" as Entity

Client -> Entity: GET
Entity --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""etag:"" | //entity-tag// |
  | ""last-modified:"" | //HTTP-date// |
end note
hnote over Client #darkseagreen: ""body""
...
Client -> Entity: GET
rnote right #lightblue
  <#lightblue,lightblue>|= Header |= Value |
  | ""if-none-match:"" | //entity-tag// |
  | ""if-modified-since:"" | //HTTP-date// |
end note
Entity --> Client: 304 Not Modified

@enduml
