@startuml
!include ../../copyright.iuml

title Conditional Operation

actor Client
participant "<&badge> Entity" as Entity

Client -> Entity: GET
Entity --> Client
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""ETag"" | //entity-tag// |
  | ""Last-Modified"" | //HTTP-date// |
end note
...
Client -> Entity: PUT / POST / PATCH / DELETE
rnote right #lightblue
  <#lightblue,lightblue>|= Header |= Value |
  | ""If-Unmodified-Since"" | //HTTP-date// |
  | ""If-Match"" | //entity-tag// |
end note
hnote over Entity #lightsteelblue
  ""    payload""
  //omitted for DELETE//
end note
Entity --> Client: 204 No Content
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""ETag"" | //entity-tag// |
  | ""Last-Modified"" | //HTTP-date// |

  // omitted for DELETE//
end note
group failure: rejected
  Entity -->o Client: 412 Precondition Failed
  Entity -->o Client: 428 Precondition Required
end

@enduml