@startuml
!include ../../copyright.iuml

title Sequential Checkout Process

rectangle "Add to Cart" as AddCart
rectangle "Select Shipping Address" as Shipping
rectangle "Set Payment" as Payment
rectangle "Complete Order" as Order

AddCart --> Shipping: blocks
Shipping --> Payment: blocks
Payment --> Order: blocks

@enduml