@startuml
!include ../../copyright.iuml

title Parallel Checkout Process

rectangle "Add to Cart" as AddCart
rectangle "Select Shipping Address" as Shipping
rectangle "Set Payment" as Payment
rectangle "Complete Order" as Order

AddCart --> Shipping: blocks
AddCart --> Payment: blocks
Shipping --> Order: blocks
Payment --> Order: blocks

@enduml