@startuml
!include ../../copyright.iuml

title Process Pattern

rectangle "<&info> | <&aperture> Process" as Process
rectangle "<&question-mark> Activity" as Activity

Process 0-->> "1..N" Activity: "activity"
Activity 0-->> Process: "process"
Activity 0~~>> Activity: "blocks, blocked-by"

@enduml