@startuml
!include ../../copyright.iuml

title Discovery

actor Client
participant "<&eye> Lookup" as Lookup

Client -> Lookup: HEAD
Lookup --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""allow:"" | ""HEAD,GET,POST"" |
  | ""content-type:"" | //content-type// |
  | ""profile:"" | ""<https://level3.rest/profiles/lookup>"" |
end note

@enduml
