@startuml
!include ../../copyright.iuml

title Discovery

actor Client
participant "<&aperture> Nexus" as Nexus

Client -> Nexus: HEAD
Nexus --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""allow:"" | ""HEAD,GET,DELETE"" |
  | *""content-type:"" | //content-type// |
  | ""profile:"" | ""<https://level3.rest/profiles/nexus>"" |

  //* stateful Nexus resources //
end note

@enduml
