@startuml
!include ../../copyright.iuml

title Discovery

actor Client
participant "<&aperture> Nexus" as Nexus

Client -> Nexus: HEAD
Nexus --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""Allow"" | ""HEAD,GET,DELETE"" |
  | ""Content-Type"" | //content-type// |
  | ""Profile"" | ""<http://level3.rest/profiles/nexus>"" |
end note

@enduml