@startuml
!include ../../copyright.iuml

title Remove Nexus

actor Client
participant "<&aperture> Nexus" as Nexus

Client -> Nexus: DELETE
Nexus --> Client: 204 No Content
...
Client -> Nexus: GET
Nexus --> Client: 404 Not Found\n410 Gone

@enduml