openapi: 3.0.0
info:
  title: HTTP/1.1 Base Specifications
  description: Shared components described in HTTP/1.1
  version: 0.0.0
  contact:
    name: Matt Bishop
    url: 'https://level3.rest'
paths:
  /donotuse:
    description: Quiets down the validator
components:
  schemas:
    wildcard:
      description: The wildcard character
      type: string
      pattern: "\\*"
    media-type:
      description: 'See [Media Type Specifications](https://tools.ietf.org/html/rfc6838)'
      type: string
      pattern: "\\w+/[-.\\w]+(?:\\+[-.\\w]+)?"
    entity-tag:
      description: 'See [HTTP/1.1 entity-tag format](https://tools.ietf.org/html/rfc2616#section-3.11)'
      type: string
      pattern: '(?:W/)"?.*"'
    HTTP-date:
      description: 'See [HTTP/1.1 date format](https://tools.ietf.org/html/rfc2616#section-3.3.1)'
      type: string
      pattern: "(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun), [0123]\\d (?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \\d\\d\\d\\d [012]\\d:[012345]\\d:[012345]\\d GMT"
    HTTP-date-list:
      description: List of HTTP-dates. Format will depend on where the schema is applied.
      type: array
      items:
        $ref: '#/components/schemas/HTTP-date'
  headers:
    ETag:
      description: 'See [HTTP/1.1 ETag](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.19)'
      schema:
        $ref: '#/components/schemas/entity-tag'
    Last-Modified:
      description: 'See [HTTP/1.1 Last-Modified](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.29)'
      schema:
        $ref: '#/components/schemas/HTTP-date'
    If-Modified-Since:
      description: 'See [HTTP/1.1 If-Modified-Since](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.25)'
      schema:
        $ref: '#/components/schemas/HTTP-date'
    If-Unmodified-Since:
      description: 'See [HTTP/1.1 If-Unmodified-Since](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.28)'
      schema:
        $ref: '#/components/schemas/HTTP-date'
    If-Range:
      description: 'See [HTTP/1.1 If-Range](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.28)'
      schema:
        oneOf:
          - $ref: '#/components/schemas/entity-tag'
          - $ref: '#/components/schemas/HTTP-date'
    If-Match:
      description: 'See [HTTP/1.1 If-Match](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.24)'
      schema:
        oneOf:
          - $ref: '#/components/schemas/wildcard'
          - $ref: '#/components/schemas/HTTP-date-list'
    If-None-Match:
      description: 'See [HTTP/1.1 If-None-Match](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.26)'
      schema:
        $ref: '#/components/headers/If-Match/schema'
    Link:
      description: 'See [Web Linking](https://tools.ietf.org/html/rfc8288)'
      example: 'Link: <http://example.com/TheBook/chapter2>; rel="previous";title="previous chapter"'
      schema:
        type: array
        items:
          allOf:
            - type: string
              description: A URL target.
              pattern: "<\\S+>"
            - type: object
              properties:
                rel:
                  description: Relation name. Whitespaced list of named ((registered) [https://www.iana.org/assignments/link-relations/link-relations.xhtml] or unregistered) and extension URI relations.
                  type: array
                  items:
                    type: string
                title:
                  description: A human-readable text describing the link.
                  type: string
                'title*':
                  description: An alternate human-readable text describing the link. See [How to encode non-ascii text] (https://tools.ietf.org/html/rfc2231)
                  type: string
                type:
                  $ref: "#/components/schemas/media-type"
                anchor:
                  description: Anchor point in the resource.
                  type: string
              required:
                - rel
servers:
  - url: none
    description: Quiets down the validator
