@startuml
!include ../../copyright.iuml

title Configure Pagination
actor Client
participant "<&spreadsheet> Pagination" as Pagination

Client -> Pagination: POST
Pagination --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""Location"" | //Paged Resource URL// |
end note
@enduml