@startuml
!include ../../copyright.iuml

title Discovery

actor Client
participant "<&home> Home" as Home

Client -> Home: HEAD
Home --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""allow:"" | ""HEAD,GET"" |
  | ""profile:"" | ""<https://level3.rest/profiles/home>"" |
end note

@enduml
