@startuml
!include ../../copyright.iuml

title Discovery

actor Client
participant "<&home> Home" as Home

Client -> Home: HEAD
Home --> Client: 204 No Content
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""Allow"" | ""HEAD,GET"" |
  | ""Profile"" | ""<http://level3.rest/profiles/home>"" |
end note

@enduml
