@startuml
!include ../../copyright.iuml

title Discovery

actor Client
participant "<&data-transfer-upload> Upload" as Upload

Client -> Upload: HEAD / GET
Upload --> Client: 200 OK
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""allow:"" | ""HEAD,GET,POST"" |
  | ""profile:"" | ""<https://level3.rest/profiles/upload>"" |
end note

@enduml
