@startuml
!include ../../copyright.iuml

title Discovery

actor Client
participant "<&project> Async" as Async

Client -> Async: HEAD
Async --> Client
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""Profile:"" | ""<https://level3.rest/profiles/mixins/async>"", |
  | | ""<other-profile>"" |
end note

@enduml