@startuml
!include ../../copyright.iuml

title Discovery

actor Client
participant "<&share> Alias" as Alias

Client -> Alias: HEAD
Alias --> Client: 307 Temporary Redirect /\n308 Permanent Redirect
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""Location"" | //target URL// |
  | ""Allow"" | //target's ""Allow"" values// |
  | ""Profile"" | ""<https://level3.rest/profiles/alias>"", |
  | | ""<target-profile>"" |
end note

@enduml
