@startuml
!include ../../copyright.iuml

title Discovery

actor Client
participant "<&share> Alias" as Alias

Client -> Alias: HEAD
Alias --> Client: 307 Temporary Redirect /\n308 Permanent Redirect
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""location:"" | //target URI// |
  | ""allow:"" | //target's ""Allow"" values// |
  | ""profile:"" | ""<https://level3.rest/profiles/alias>"", |
  | | ""<target-profile>"" |
end note

@enduml
