@startuml
!include ../../copyright.iuml

title Operate Alias

actor Client
participant "<&share> Alias" as Alias

Client -> Alias: GET / PUT / POST / PATCH / DELETE
Alias --> Client: 307 Temporary Redirect /\n308 Permanent Redirect
rnote left #lightgreen
  <#lightgreen,lightgreen>|= Header |= Value |
  | ""Location"" | //Target URL// |
end note
Client -> Target: GET / PUT / POST / PATCH / DELETE

@enduml
